//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoChecker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoChecker.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92991381-346a-4129-8068-4561f0cf6e3c.
        /// </summary>
        internal static string API_Key {
            get {
                return ResourceManager.GetString("API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUD.
        /// </summary>
        internal static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRL.
        /// </summary>
        internal static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD,EUR,BRL,GBP,AUD.
        /// </summary>
        internal static string converts {
            get {
                return ResourceManager.GetString("converts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        internal static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest.
        /// </summary>
        internal static string QuotesURL {
            get {
                return ResourceManager.GetString("QuotesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
    }
}
